name: Build OpenTTD Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    uses: ./.github/workflows/docker-image.yml
    with:
      push: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
